/**
 * Textos de UI centralizados: sem string literal em JSX (ver SPEC.md,
 * "Arquitetura Frontend").
 */
export const TEXTOS = {
  app: {
    titulo: 'SRM Credit Engine',
    subtitulo: 'Precificação e registro auditável de lotes de recebíveis',
  },
  form: {
    tituloSecao: 'Novo lote de recebíveis',
    subtituloSecao: 'O ativo é sempre negociado em reais (BRL). Escolha a moeda de pagamento apenas se o pagamento ocorrer em moeda diferente.',
    legendaRecebivel: 'Recebível',
    ativo: 'Ativo',
    valorBruto: 'Valor bruto (R$)',
    valorBrutoPlaceholder: 'Ex.: 15000.00',
    moedaPagamento: 'Moeda de pagamento',
    dataVencimento: 'Data de vencimento',
    categoriaRisco: 'Categoria de risco',
    adicionarRecebivel: '+ Adicionar recebível',
    removerRecebivel: 'Remover',
    enviar: 'Precificar lote',
    enviando: 'Precificando...',
    sucesso: 'Lote registrado com sucesso.',
  },
  erros: {
    ativoObrigatorio: 'Ativo é obrigatório',
    valorBrutoObrigatorio: 'Valor bruto é obrigatório',
    valorBrutoInvalido: 'Informe um número válido, com ponto para casas decimais (ex.: 1000.50)',
    valorBrutoPositivo: 'Valor bruto deve ser positivo',
    dataVencimentoObrigatoria: 'Data de vencimento é obrigatória',
    loteVazio: 'Adicione ao menos um recebível',
    erroGenerico: 'Não foi possível processar a solicitação. Tente novamente.',
  },
  tabela: {
    tituloSecao: 'Lotes recebidos',
    colunaDataReferencia: 'Data de referência',
    colunaStatus: 'Status',
    colunaCriadoEm: 'Criado em',
    colunaAcoes: 'Ações',
    vazio: 'Nenhum lote encontrado.',
    carregando: 'Carregando lotes...',
    erro: 'Erro ao carregar lotes.',
    verDetalhe: 'Ver detalhe',
    anterior: 'Anterior',
    proxima: 'Próxima',
    pagina: 'Página',
  },
  detalhe: {
    voltar: '← Voltar para a listagem',
    tituloSecao: 'Recebíveis do lote',
    colunaAtivo: 'Ativo',
    colunaValorBruto: 'Valor bruto (R$)',
    colunaMoedaPagamento: 'Moeda de pagamento',
    colunaValorPresente: 'Valor presente',
    colunaDesagio: 'Deságio (R$)',
    colunaTaxa: 'Taxa aplicada',
    colunaStatus: 'Status',
    colunaMotivo: 'Motivo',
    carregando: 'Carregando lote...',
    erro: 'Erro ao carregar o lote.',
    naoEncontrado: 'Lote não encontrado.',
  },
  status: {
    RECEBIDO: 'Recebido',
    PRECIFICADO: 'Precificado',
    ERRO: 'Erro',
    PENDENTE: 'Pendente',
    REJEITADO: 'Rejeitado',
  },
  moedas: {
    BRL: 'Real (BRL)',
    USD: 'Dólar (USD)',
  },
  categoriasRisco: {
    AA: 'AA — risco mínimo',
    A: 'A — risco baixo',
    B: 'B — risco moderado',
    C: 'C — risco médio-alto',
    D: 'D — risco alto',
    E: 'E — risco elevado',
  },
} as const
