/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/lotes-recebiveis/{loteId}/recebiveis/{recebivelId}/liquidacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Liquida um recebivel precificado
         * @description Marca o recebivel como LIQUIDADO (paga o valorPresente ao cedente, na moeda de pagamento). PUT em vez de POST deliberadamente: a operacao e' idempotente - chamar novamente um recebivel ja liquidado (retry de rede, duplo clique) retorna 200 com o mesmo resultado, sem gerar uma nova liquidacao ou efeito colateral (ver SPEC.md).
         */
        put: operations["liquidar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lotes-recebiveis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os lotes de recebiveis, paginado
         * @description Ordenacao por createdAt, dataReferencia ou status (formato: campo,asc|desc).
         */
        get: operations["listar"];
        put?: never;
        /**
         * Recebe e precifica um lote de recebiveis
         * @description Calcula o desagio de cada recebivel do lote e registra o resultado de forma auditavel. Retorna 201 mesmo se algum recebivel for rejeitado individualmente (ver campo status de cada item).
         */
        post: operations["criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lotes-recebiveis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca o detalhe de um lote, com seus recebiveis precificados */
        get: operations["buscarPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecebivelResponse: {
            /** Format: uuid */
            id?: string;
            ativo?: string;
            /** @example 15000.00 */
            valorBruto?: string;
            /** @enum {string} */
            moeda?: "BRL" | "USD";
            /** Format: date */
            dataVencimento?: string;
            /** @enum {string} */
            categoriaRisco?: "AA" | "A" | "B" | "C" | "D" | "E";
            /** @enum {string} */
            status?: "PENDENTE" | "PRECIFICADO" | "REJEITADO" | "LIQUIDADO";
            /** @example 14200.00 */
            valorPresente?: string;
            /** @example 800.00 */
            valorDesagio?: string;
            /** @example 0.146500 */
            taxaDescontoAplicada?: string;
            motivoRejeicao?: string;
            /**
             * @description Moeda em que o recebivel e' efetivamente pago; igual a `moeda` quando nao ha conversao cambial.
             * @enum {string}
             */
            moedaPagamento?: "BRL" | "USD";
            /**
             * @description Cotacao (BRL por 1 USD) usada na conversao; null quando moedaPagamento == moeda.
             * @example 5.20
             */
            cotacaoCambio?: string;
            /**
             * Format: date-time
             * @description Data/hora em que o recebivel foi liquidado (pago ao cedente); null enquanto nao liquidado.
             */
            liquidadoEm?: string;
        };
        LoteRecebiveisRequest: {
            recebiveis: components["schemas"]["RecebivelRequest"][];
        };
        RecebivelRequest: {
            ativo: string;
            /** @example 15000.00 */
            valorBruto: string;
            /** Format: date */
            dataVencimento: string;
            /** @enum {string} */
            categoriaRisco: "AA" | "A" | "B" | "C" | "D" | "E";
            /**
             * @description Moeda em que o recebivel e' efetivamente pago, se diferente de BRL (cross-currency). Omitir quando o pagamento e' em BRL (mesma moeda do ativo).
             * @enum {string}
             */
            moedaPagamento?: "BRL" | "USD";
        };
        LoteRecebiveisResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            dataReferencia?: string;
            /** @enum {string} */
            status?: "RECEBIDO" | "PRECIFICADO" | "ERRO";
            recebiveis?: components["schemas"]["RecebivelResponse"][];
        };
        LoteRecebiveisResumoResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            dataReferencia?: string;
            /** @enum {string} */
            status?: "RECEBIDO" | "PRECIFICADO" | "ERRO";
            /** Format: date-time */
            createdAt?: string;
        };
        PaginaResponseLoteRecebiveisResumoResponse: {
            content?: components["schemas"]["LoteRecebiveisResumoResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liquidar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loteId: string;
                recebivelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recebivel liquidado (ou ja estava liquidado - idempotente) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecebivelResponse"];
                };
            };
            /** @description Lote ou recebivel nao encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecebivelResponse"];
                };
            };
            /** @description Recebivel nao esta PRECIFICADO (nunca precificado ou rejeitado) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecebivelResponse"];
                };
            };
        };
    };
    listar: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaResponseLoteRecebiveisResumoResponse"];
                };
            };
        };
    };
    criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteRecebiveisRequest"];
            };
        };
        responses: {
            /** @description Lote recebido e processado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoteRecebiveisResponse"];
                };
            };
        };
    };
    buscarPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoteRecebiveisResponse"];
                };
            };
        };
    };
}
